import jsPDF from 'jspdf';
import { RefinedPrompt } from '@/types/interface';

type PDFTemplate = 'minimalist' | 'modern-dark' | 'classic-script';

export const exportToPDF = (refined: RefinedPrompt, template: PDFTemplate = 'minimalist') => {
  const doc = new jsPDF();
  const { refined_prompt, explanation, title } = refined;
  const fileName = `${title || 'refined-prompt'}.pdf`;

  if (template === 'minimalist') {
    // Minimalist Template
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text(title || 'Prompt Strategy', 20, 30);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 35, 190, 35);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by PromptLab • ${new Date().toLocaleDateString()}`, 20, 42);

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text('REFINED PROMPT', 20, 60);
    
    doc.setFont('courier', 'normal');
    doc.setFontSize(11);
    const splitPrompt = doc.splitTextToSize(refined_prompt, 170);
    doc.text(splitPrompt, 20, 70);

    const promptHeight = (splitPrompt.length * 5) + 80;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('EXPLANATION', 20, promptHeight);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const splitExp = doc.splitTextToSize(explanation || '', 170);
    doc.text(splitExp, 20, promptHeight + 10);

  } else if (template === 'modern-dark') {
    // Modern Dark Template
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 297, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(26);
    doc.text(title || 'PROMPT LAB', 20, 40);

    doc.setDrawColor(59, 130, 246); // blue-500
    doc.setLineWidth(1.5);
    doc.line(20, 45, 60, 45);

    doc.setTextColor(148, 163, 184); // slate-400
    doc.setFontSize(10);
    doc.text('OPTIMIZED OUTPUT', 20, 65);

    doc.setFillColor(30, 41, 59); // slate-800
    doc.roundedRect(20, 70, 170, 100, 5, 5, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFont('courier', 'bold');
    doc.setFontSize(12);
    const splitPrompt = doc.splitTextToSize(refined_prompt, 150);
    doc.text(splitPrompt, 30, 85);

    doc.setTextColor(148, 163, 184);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const splitExp = doc.splitTextToSize(explanation || '', 170);
    doc.text(splitExp, 20, 185);

  } else if (template === 'classic-script') {
    // Classic Script Template
    doc.setFont('times', 'italic');
    doc.setFontSize(28);
    doc.text(title || 'The Engineered Word', 105, 40, { align: 'center' });
    
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);
    doc.line(50, 45, 160, 45);

    doc.setFont('times', 'normal');
    doc.setFontSize(12);
    const splitPrompt = doc.splitTextToSize(refined_prompt, 150);
    doc.text(splitPrompt, 30, 70);

    doc.setFont('times', 'bold');
    doc.text('The Rationale', 30, 150);
    doc.setFont('times', 'normal');
    const splitExp = doc.splitTextToSize(explanation || '', 150);
    doc.text(splitExp, 30, 160);
  }

  doc.save(fileName);
};
